### ISSUE TITLE
Agree on list of E-SOH KPI's

### ISSUE THREAD

**Issue by GijsbertKruithof** [EURODEO/e-soh-kpis#2] opened 2023-04-11 11:30 UTC
.. within the E-SOH team.

**Comment by tervo** [comment] 2023-04-21 07:42
Some views on the initial list provided in initial discussion: 
- Availability of API-service  - uptime % 
                                                                                                                                                                                                      _Valid and important measure to make sure the service is available_                                                                                                                                                                               

- API response time - average API requests response time            

_Valid and important measure to make sure API is responding in reasonable time (it's usable)_                                                                                                                                                     

- API error rate - This measures the percentage of requests that result in errors.                                     
- Download success                                                                                                                                                                                                                              _Not so good as KPI as errors are often also caused by incorrect requests. Good for monitoring._  

-   Number of unique API users    

_Valid KPI for stakeholders but might be a bit challenging to measure before we get proper insight analytics if API key is not used._           

 - Amount of data transferred via JSON                          
 
 _Do we have specific goal to change all data transfer to JSON?_                                                                                                                                                                                   

- Download rate               
                                                                                                                                                                                                            _Valid and coupled with response time_                   

 - Amount of NMH's with data available via the API                                                                      
 - Total amount of data available                                                                                       
 - Amount of Weather Stations available via the API

**Comment by tervo** [comment] 2023-04-21 07:57
Some more views: 

- Number of unique API users                                                                                            

_Valued KPI if we can easily get this. With more advanced analytics we can get quite reliable measure using combination of IP address, user agent, operating system, and referrer. _

- Number of API calls in a month

_Valid KPI_
                                                                                       
- Source of API calls

_Do we have specific goals for this? Maybe more to monitoring? Although it would be nice to report for management_
                                                                                                   
- Amount of data transferred via JSON

_Do we have specific goal to move everything to JSON? Probably also not so much stakeholder KPI unless we want to communicate this?__
                                                                                   
- Amount of NMHS's with data available via the API

_Valid KPI to see NMHS uptake_
                                                                       
- Total amount of data available

_Kind of valid KPI but does this figure tell anything?_
                                                                                       
- Amount of Weather Stations available via the API  

_I guess it's telling well the uptake of NMHS with understandable figure. Would help if it's reported with the total amount of weather stations. The only problem is that this is a bit E-SOH specific and can't be applied to other data types._

**Comment by tervo** [comment] 2023-04-21 11:53
I would argue that System/Software KPIs are not needed (Meantime to recovery - MTTR, Mean Time Between Failures - MTBF, Average issue handle time) are not needed. I think the availability KPI is sufficient. If something is taken from here, I would take the issue handle time or time to first response, but I would use also those only if there's any problems.

**Comment by tervo** [comment] 2023-04-21 13:16
Copying data ingestion initial list of KPIs here:                                                                                        
- System uptime %                                                                                                      
- Ingestion success rate - the percentage of data that is successfully ingested                                        
- Ingestion time                                                                                                       
- Data transformation success rate - the percentage of BUFR files that is successfully transformed by the system                                                                                                                                - Data timelines

**Comment by tervo** [comment] 2023-04-22 09:57
I would propose we drop data and metadata quality KPIs because they probably can not be automatically monitored/reported. Or do we have any easy way to do that?

**Comment by GijsbertKruithof** [comment] 2023-04-25 11:06
I agree with you Roope on dropping the metadata quality KPI's and the system/software KPI's, but we need to confirm this with the others
I'll move this to issue to the Discussion lane

**Closed as completed** 2023-04-28 12:35 UTC
